### ISSUE TITLE
Infografía Hilos

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/infografia-de-hilos-garaudy12#2]
[Infografía Hilos - Solano Mendoza Taolí Garaudy.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-garaudy12/files/6469148/Infografia.Hilos.-.Solano.Mendoza.Taoli.Garaudy.pdf)

**Comment by MLR062998** [comment]
calificación: 20/20
califico: Manuel lopez

**Comment by josealfredo79** [comment]
Bien hecho y revisado
